### ISSUE TITLE
Jittery user experience on Chromium

### ISSUE THREAD

**Issue by rahul-kurup** [Joshua-Riek/ubuntu-rockchip#193]
As it says in the title, I've faced jittery mouse movements when using Chromium. For example, if I'm playing a video on YouTube, mouse (connected via [bluetooth 4.0 adapter](https://hideez.com/en-int/products/hideez-dongle)) starts to jitter a lot. 
Sometimes video playback also skips a frame or two, when the jitter happens. I keep video resolution at 1080p only.
This jittery experience also happens in Armbian 23.5 Jammy, but in that case it's too extreme; to the point where I cannot use Chromium at all.  
I'm guessing it's because of the updated kernel. 
Not sure whether you/others have faced the issue or not.

**Comment by Joshua-Riek** [comment]
Sadly, Chromium issues are not something I can assist with or fix, and it's out of my current knowledge. It could be due to the kernel, as more than 6000 new commits were added, and it's impossible to go through every change made. 

There is another kernel release from Rockchip (linux-5.10-gen-rkr4.1) but this time, only 150 commits. Sadly I don't have patch notes, but I see changes related to video / HDMI and the vpu. This may help in this area, especially with video playback. However, I'm still fixing issues with the current kernel and have yet to have time to test the latest release from Rockchip. I only made sure that It could boot.
