### ISSUE TITLE
No HDMI sound devices in Gnome Sound settings

### ISSUE THREAD

**Issue by ndrewpj** [Joshua-Riek/ubuntu-rockchip#429]
Hi there! I got no sound devices for HDMI output in Gnome's sound settings (I got a monitor with speakers), but in the console I see them. What could I do with this?

**Comment by Joshua-Riek** [comment]
Eh what board?

**Comment by ndrewpj** [comment]
sorry, forgot it - Orangepi 5 plus, latest release of your OS

**Comment by Joshua-Riek** [comment]
I just tested the latest release, and HDMI audio works fine on the Orange Pi 5 Plus. Maybe you installed a package that causes audio conflicts.

**Comment by JFLim1** [comment]
> I just tested the latest release, and HDMI audio works fine on the Orange Pi 5 Plus.

Hi @Joshua-Riek,

Everytime the Orange Pi 5 Plus is rebooted Sound Output device is reset to "Speakers - ES8388 Audio" eventhough it was set to "Analog Output - HDMI0 Audio" using the "Gnome Settings".  Somehow Sound settings will reset to "Speakers - ES8388 Audio" when you reboot.

**Comment by bagong** [comment]
Audio works, but as JFLim1 described, doesn't stick when set to hdmi0 or 1.

**Comment by bagong** [comment]
Since I switched to pipewire for audio as well (following https://gist.github.com/the-spyke/2de98b22ff4f978ebf0650c90e82027e?permalink_comment_id=3976215), the audio device sticks through reboot. Now however the names - audio analog, hdmi0 and hdmi1 - are not distinguished, all three outputs are called "Analog output - built in Audio". One can however switch properly, and as I said, it sticks.
