### ISSUE TITLE
No name RK3588 Board

### ISSUE THREAD

**Issue by irlkitcom** [Joshua-Riek/ubuntu-rockchip#456]
Hello,

I have a no name RK3588 board. It came with Android 12 installed. I contacted the seller and they don't have an image for it for Linux. Is there any chance this board could run Ubuntu?

**Comment by Joshua-Riek** [comment]
Sure if you reverse engineer the device tree. But I will not help with this.

**Comment by ferrellsl** [comment]
If you provided a good photo of your board we might be able to tell what it was cloned from.  More than likely it's a copy of a 5 or 5b.



 

    On Thursday, November 9, 2023 at 02:12:53 AM MST, IRLKit ***@***.***> wrote:  
 
 


Hello,

I have a no name RK3588 board. It came with Android 12 installed. I contacted the seller and they don't have an image for it for Linux. Is there any chance this board could run Ubuntu?

**Comment by irlkitcom** [comment]
> If you provided a good photo of your board we might be able to tell what it was cloned from.  More than likely it's a copy of a 5 or 5b. On Thursday, November 9, 2023 at 02:12:53 AM MST, IRLKit ***@***.***> wrote: Hello, I have a no name RK3588 board. It came with Android 12 installed. I contacted the seller and they don't have an image for it for Linux. Is there any chance this board could run Ubuntu? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


![](https://i.imgur.com/mMtGMex.jpg)

**Comment by ferrellsl** [comment]
That looks a lot like a Mekotronics R58 Mini.  I own a Mini and it came pre-loaded with Android TV OS 12.  Do you get any hints as to what hardware or OS you're running when you look under the Settings->About?
Here's what mine says:



 

    On Thursday, November 9, 2023 at 05:09:40 PM MST, IRLKit ***@***.***> wrote:  
 
 



If you provided a good photo of your board we might be able to tell what it was cloned from.  More than likely it's a copy of a 5 or 5b. On Thursday, November 9, 2023 at 02:12:53 AM MST, IRLKit @.> wrote: Hello, I have a no name RK3588 board. It came with Android 12 installed. I contacted the seller and they don't have an image for it for Linux. Is there any chance this board could run Ubuntu? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

**Comment by irlkitcom** [comment]
> That looks a lot like a Mekotronics R58 Mini.  I own a Mini and it came pre-loaded with Android TV OS 12.  Do you get any hints as to what hardware or OS you're running when you look under the Settings->About? Here's what mine says: On Thursday, November 9, 2023 at 05:09:40 PM MST, IRLKit ***@***.***> wrote: If you provided a good photo of your board we might be able to tell what it was cloned from.  More than likely it's a copy of a 5 or 5b. On Thursday, November 9, 2023 at 02:12:53 AM MST, IRLKit @.> wrote: Hello, I have a no name RK3588 board. It came with Android 12 installed. I contacted the seller and they don't have an image for it for Linux. Is there any chance this board could run Ubuntu? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Everything in the About section just says RK3588_S, even though the chip on the board is 100% an RK3588 non S variant. It's running Android 12 Tablet version.
