### ISSUE TITLE
How to change usbcore /sys/module/usbcore/parameters/autosuspend ?

### ISSUE THREAD

**Issue by artem-zinnatullin** [Joshua-Riek/ubuntu-rockchip#659]
Hi,

I'm trying to troubleshoot USB Zigbee dongle disconnects and the suggested solution here https://www.zigbee2mqtt.io/guide/faq/#zigbee2mqtt-crashes-after-some-time is to disable USB autosuspend via Grub setting.

On ubuntu-rockchip v1.33 the USB Autosuspend seems to be set to 2 which allows auto powering off after 2 seconds of inactivity:

```js
cat /sys/module/usbcore/parameters/autosuspend
2
```

However the distro doesn't seem to have active Grub config wired up in a default Ubuntu way (correct me if I'm wrong please):

```js
find / -name "grub.cfg"
# no results
```

How does one change the usbcore `/sys/module/usbcore/parameters/autosuspend` setting so that it persists after reboots?

Linux Kernel docs imply that this setting is distro-specific and depends on how distro loads them up during boot and/or how the usbcore module is compiled-in: https://www.kernel.org/doc/html/v5.10/driver-api/usb/power-management.html#changing-the-default-idle-delay-time so I wanted to clarify with you @Joshua-Riek :)

Related issue: #427

**Comment by guelermus** [comment]
Hi,
For an ARM system, it may help to try the modprobe approach from here:
https://unix.stackexchange.com/questions/91027/how-to-disable-usb-autosuspend-on-kernel-3-7-10-or-above
Best,

**Comment by KaMyKaSii** [comment]
I'm having problems with the mount point of an external HD returning "Input/output error" and when researching I ended up here and discovered that perhaps USB suspension is the cause of this problem. Searching further, I found that to disable USB suspension you need to edit the file `/boot/extlinux/extlinux.conf` and add `usbcore.autosuspend=-1` at the end of the 'append' line, so for example `append root=UUID=0114e383-defc-4a40-a8cf-81726e56d66a rootwait rw console=ttyS2,1500000 console=tty1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory` will become `append root=UUID=0114e383-defc-4a40-a8cf-81726e56d66a rootwait rw console=ttyS2,1500000 console=tty1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory usbcore.autosuspend=-1`. As the file itself suggests, the configuration file will be overwritten if the "u-boot-update" utility is run, I believe this happens when Ubuntu Rockchip receives updates
